version: "3.1"

services:
  labDb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootkit
      MYSQL_DATABASE: smartlab
      MYSQL_USER: root
    volumes:
      - /home/sasori/Downloads/cleaningJS/Docker/mysql:/var/lib/mysql
    networks:
      - public
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - labDb:mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: labDb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootkit
      depends_on: labDb
    volumes:
      - /home/sasori/Downloads/cleaningJS/Docker/phpmyadmin:/usr/local/etc/php/php.ini
    networks:
      - public

networks:
  public:
